# Generated by Django 6.0.6 on 2026-07-01 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(default='movie', max_length=50)),
                ('genres', models.JSONField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('creators', models.JSONField(blank=True, null=True)),
                ('seasons', models.IntegerField(blank=True, null=True)),
                ('seasons_seen', models.IntegerField(blank=True, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
                ('years', models.CharField(blank=True, max_length=50, null=True)),
                ('directors', models.JSONField(blank=True, null=True)),
                ('writers', models.JSONField(blank=True, null=True)),
                ('runtime_minutes', models.IntegerField(blank=True, null=True)),
                ('cast', models.JSONField(blank=True, null=True)),
                ('title_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_image_paths', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='not_seen', max_length=20)),
                ('is_seen', models.BooleanField(default=False)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('user_review', models.TextField(blank=True, null=True)),
                ('scale_type', models.CharField(blank=True, max_length=20, null=True)),
                ('entertaining_rating', models.FloatField(blank=True, null=True)),
                ('momentum_rating', models.FloatField(blank=True, null=True)),
                ('characters_rating', models.FloatField(blank=True, null=True)),
                ('rewatchability_rating', models.FloatField(blank=True, null=True)),
                ('immersive_rating', models.FloatField(blank=True, null=True)),
                ('stakes_rating', models.FloatField(blank=True, null=True)),
                ('heart_rating', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'media_items',
                'ordering': ['-added_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RatingWeights',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scale_type', models.CharField(max_length=20, unique=True)),
                ('entertaining_weight', models.FloatField(default=0.25)),
                ('momentum_weight', models.FloatField(default=0.25)),
                ('characters_weight', models.FloatField(default=0.25)),
                ('rewatchability_weight', models.FloatField(default=0.25)),
                ('immersive_weight', models.FloatField(default=0.25)),
                ('stakes_weight', models.FloatField(default=0.25)),
                ('heart_weight', models.FloatField(default=0.25)),
            ],
            options={
                'db_table': 'rating_weights',
                'managed': True,
            },
        ),
    ]
