# Generated by Django 6.0.6 on 2026-08-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlmProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=32)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_key_env', models.CharField(blank=True, max_length=120)),
                ('default_model', models.CharField(blank=True, max_length=200)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('connect_timeout', models.FloatField(default=5.0)),
                ('timeout', models.FloatField(default=180.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
