"""Generate the README banner from the project logo. Run: python3 tools/make_header.py"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGO = ROOT / "docs/assets/mango-color.svg"
LOGO_BOX = (0, 0, 1043.4088, 1031.8049)    # the logo's own viewBox
CROP = (0, 0, 1043.4088, 812.0)            # the part to show: the tree, not its wordmark
OUT = ROOT / "docs/assets/header.svg"

TITLE = "Mango Tree"
TAGLINE = (
    "A local-first, single-owner agent platform: eight self-hosted apps and",
    "a LangGraph agent reach the same services, all on your own machine.",
)
LANGUAGES = [
    ("Python", "#3572a5"),
    ("TypeScript", "#3178c6"),
    ("CSS", "#663399"),
]
STACK = [(n, None) for n in ("Django", "DRF", "LangGraph", "React", "SQLite", "uv")]

PANEL_BG, PANEL_EDGE = "#0a0c0d", "#1c2123"
CHIP_BG, CHIP_EDGE = "#101415", "#2a3033"
TEXT, CHIP_TEXT, MUTED = "#e9e6df", "#c9ccc7", "#8e948f"
DISC = "#f6f2e8"                           # light disc behind the logo; None to skip it
DISC_R = 96.0                              # wide enough that the drawing never touches the edge

SANS = "ui-sans-serif,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif"
MONO = "ui-monospace,SFMono-Regular,Menlo,Consolas,'DejaVu Sans Mono',monospace"

W = 1000
MARK, MARK_CY = 148.0, 126.0                # logo size, and its centre from the top
TITLE_Y, TITLE_SIZE = 278, 66
TAGLINE_Y, TAGLINE_SIZE, LINE_H = 316, 19, 28
ROWS_Y, ROW_H = 386, 46                     # first chip row, and the gap to the next
CHIP_H, CHIP_FS, CHIP_GAP, CHIP_PAD = 32, 14.0, 10.0, 15.0
DOT_R, DOT_GUTTER, ADVANCE = 4.0, 13.0, 0.6

rows = [r for r in (LANGUAGES, STACK) if r]
H = int(ROWS_Y + ROW_H * (len(rows) - 1) + CHIP_H + 24)


def logo_paths():
    """The logo's children, minus the editor bookkeeping GitHub would strip anyway."""
    raw = LOGO.read_text()
    body = raw[raw.index(">", raw.index("<svg")) + 1 : raw.rindex("</svg>")]
    body = re.sub(r"<metadata>.*?</metadata>", "", body, flags=re.S)
    body = re.sub(r"<sodipodi:namedview\b.*?</sodipodi:namedview>", "", body, flags=re.S)
    body = re.sub(r"<(?:sodipodi|inkscape):[\w-]+\b[^>]*/>", "", body)
    body = re.sub(r'\s+(?:sodipodi|inkscape):[\w-]+="[^"]*"', "", body)
    return body.strip()


def chip_row(items, y):
    widths = [
        CHIP_PAD * 2 + len(label) * CHIP_FS * ADVANCE + (DOT_GUTTER if dot else 0.0)
        for label, dot in items
    ]
    x = (W - (sum(widths) + CHIP_GAP * (len(items) - 1))) / 2
    parts = []
    for (label, dot), width in zip(items, widths):
        text_x = x + CHIP_PAD
        parts.append(
            f'<rect x="{x:.1f}" y="{y:g}" width="{width:.1f}" height="{CHIP_H}" '
            f'rx="{CHIP_H / 2:g}" fill="{CHIP_BG}" stroke="{CHIP_EDGE}" />'
        )
        if dot:
            parts.append(
                f'<circle cx="{text_x + DOT_R:.1f}" cy="{y + CHIP_H / 2:.1f}" '
                f'r="{DOT_R:g}" fill="{dot}" />'
            )
            text_x += DOT_GUTTER
        parts.append(
            f'<text x="{text_x:.1f}" y="{y + CHIP_H / 2 + 5:.1f}" font-family="{MONO}" '
            f'font-size="{CHIP_FS:g}" fill="{CHIP_TEXT}">{label}</text>'
        )
        x += width + CHIP_GAP
    return "\n  ".join(parts)


cx = W / 2
crop = CROP or LOGO_BOX
scale = MARK / max(crop[2], crop[3])        # fit the longer side, keep the aspect ratio
mark_w, mark_h = crop[2] * scale, crop[3] * scale
mark_x, mark_y = cx - mark_w / 2, MARK_CY - mark_h / 2
disc = (
    f'<circle cx="{cx:g}" cy="{MARK_CY:g}" r="{DISC_R:g}" fill="{DISC}" />'
    if DISC
    else ""
)
taglines = "\n  ".join(
    f'<text x="{cx:g}" y="{TAGLINE_Y + i * LINE_H:g}" text-anchor="middle" '
    f'font-family="{SANS}" font-size="{TAGLINE_SIZE}" fill="{MUTED}">{line}</text>'
    for i, line in enumerate(TAGLINE)
)
chips = "\n  ".join(chip_row(row, ROWS_Y + i * ROW_H) for i, row in enumerate(rows))

OUT.write_text(f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" \
width="{W}" height="{H}" role="img" aria-label="{TITLE}">
  <!-- Generated by tools/make_header.py - edit that, not this. -->
  <rect x="0.5" y="0.5" width="{W - 1}" height="{H - 1}" rx="24" fill="{PANEL_BG}" \
stroke="{PANEL_EDGE}" />
  {disc}
  <svg x="{mark_x:.1f}" y="{mark_y:.1f}" width="{mark_w:.1f}" height="{mark_h:.1f}" \
viewBox="{" ".join(f"{v:g}" for v in crop)}" overflow="hidden">
    {logo_paths()}
  </svg>
  <text x="{cx:g}" y="{TITLE_Y}" text-anchor="middle" font-family="{SANS}" \
font-size="{TITLE_SIZE}" font-weight="700" letter-spacing="-1" fill="{TEXT}">{TITLE}</text>
  {taglines}
  {chips}
</svg>
""")
print(f"wrote {OUT.relative_to(ROOT)}")
